const PRONOUNS = [
  { it: "io", en: "I" },
  { it: "tu", en: "you" },
  { it: "lui / lei", en: "he / she" },
  { it: "noi", en: "we" },
  { it: "voi", en: "you all" },
  { it: "loro", en: "they" },
];

const FORMS = [
  { id: "presente", it: "presente indicativo", en: "present indicative", hint: "I speak / I am" },
  { id: "passato_prossimo", it: "passato prossimo", en: "present perfect", hint: "I have spoken / I went" },
  { id: "imperfetto", it: "imperfetto", en: "imperfect", hint: "I used to speak" },
  { id: "futuro", it: "futuro semplice", en: "simple future", hint: "I will speak" },
  { id: "condizionale", it: "condizionale presente", en: "present conditional", hint: "I would speak" },
  { id: "congiuntivo_presente", it: "congiuntivo presente", en: "present subjunctive", hint: "that I speak" },
];

const VERB_DATA = [
  { id: "essere", it: "essere", en: "to be", irregular: true, aux: "essere", participle: "stato" },
  { id: "avere", it: "avere", en: "to have", irregular: true, aux: "avere", participle: "avuto" },
  { id: "fare", it: "fare", en: "to do / make", irregular: true, aux: "avere", participle: "fatto" },
  { id: "dire", it: "dire", en: "to say / tell", irregular: true, aux: "avere", participle: "detto" },
  { id: "potere", it: "potere", en: "can / to be able to", irregular: true, aux: "avere", participle: "potuto" },
  { id: "volere", it: "volere", en: "to want", irregular: true, aux: "avere", participle: "voluto" },
  { id: "dovere", it: "dovere", en: "must / to have to", irregular: true, aux: "avere", participle: "dovuto" },
  { id: "sapere", it: "sapere", en: "to know", irregular: true, aux: "avere", participle: "saputo" },
  { id: "stare", it: "stare", en: "to stay / be", irregular: true, aux: "essere", participle: "stato" },
  { id: "andare", it: "andare", en: "to go", irregular: true, aux: "essere", participle: "andato" },
  { id: "venire", it: "venire", en: "to come", irregular: true, aux: "essere", participle: "venuto" },
  { id: "dare", it: "dare", en: "to give", irregular: true, aux: "avere", participle: "dato" },
  { id: "vedere", it: "vedere", en: "to see", irregular: true, aux: "avere", participle: "visto" },
  { id: "parlare", it: "parlare", en: "to speak", irregular: false, aux: "avere", participle: "parlato" },
  { id: "trovare", it: "trovare", en: "to find", irregular: false, aux: "avere", participle: "trovato" },
  { id: "prendere", it: "prendere", en: "to take", irregular: true, aux: "avere", participle: "preso" },
  { id: "mettere", it: "mettere", en: "to put", irregular: true, aux: "avere", participle: "messo" },
  { id: "pensare", it: "pensare", en: "to think", irregular: false, aux: "avere", participle: "pensato" },
  { id: "lasciare", it: "lasciare", en: "to leave / let", irregular: false, aux: "avere", participle: "lasciato" },
  { id: "guardare", it: "guardare", en: "to watch / look at", irregular: false, aux: "avere", participle: "guardato" },
  { id: "chiamare", it: "chiamare", en: "to call", irregular: false, aux: "avere", participle: "chiamato" },
  { id: "arrivare", it: "arrivare", en: "to arrive", irregular: false, aux: "essere", participle: "arrivato" },
  { id: "passare", it: "passare", en: "to pass / spend time", irregular: false, aux: "avere", participle: "passato" },
  { id: "credere", it: "credere", en: "to believe", irregular: false, aux: "avere", participle: "creduto" },
  { id: "portare", it: "portare", en: "to bring / wear", irregular: false, aux: "avere", participle: "portato" },
  { id: "uscire", it: "uscire", en: "to go out", irregular: true, aux: "essere", participle: "uscito" },
  { id: "tornare", it: "tornare", en: "to return", irregular: false, aux: "essere", participle: "tornato" },
  { id: "sentire", it: "sentire", en: "to hear / feel", irregular: false, aux: "avere", participle: "sentito" },
  { id: "vivere", it: "vivere", en: "to live", irregular: true, aux: "avere", participle: "vissuto" },
  { id: "morire", it: "morire", en: "to die", irregular: true, aux: "essere", participle: "morto" },
  { id: "capire", it: "capire", en: "to understand", irregular: false, aux: "avere", participle: "capito", isc: true },
  { id: "mangiare", it: "mangiare", en: "to eat", irregular: false, aux: "avere", participle: "mangiato" },
  { id: "bere", it: "bere", en: "to drink", irregular: true, aux: "avere", participle: "bevuto" },
  { id: "aspettare", it: "aspettare", en: "to wait for", irregular: false, aux: "avere", participle: "aspettato" },
  { id: "cercare", it: "cercare", en: "to look for / search", irregular: false, aux: "avere", participle: "cercato" },
  { id: "entrare", it: "entrare", en: "to enter", irregular: false, aux: "essere", participle: "entrato" },
  { id: "lavorare", it: "lavorare", en: "to work", irregular: false, aux: "avere", participle: "lavorato" },
  { id: "scrivere", it: "scrivere", en: "to write", irregular: true, aux: "avere", participle: "scritto" },
  { id: "leggere", it: "leggere", en: "to read", irregular: true, aux: "avere", participle: "letto" },
  { id: "perdere", it: "perdere", en: "to lose", irregular: true, aux: "avere", participle: "perso" },
  { id: "chiedere", it: "chiedere", en: "to ask", irregular: true, aux: "avere", participle: "chiesto" },
  { id: "rispondere", it: "rispondere", en: "to answer", irregular: true, aux: "avere", participle: "risposto" },
  { id: "chiudere", it: "chiudere", en: "to close", irregular: true, aux: "avere", participle: "chiuso" },
  { id: "aprire", it: "aprire", en: "to open", irregular: true, aux: "avere", participle: "aperto" },
  { id: "conoscere", it: "conoscere", en: "to know / meet", irregular: false, aux: "avere", participle: "conosciuto" },
  { id: "comprare", it: "comprare", en: "to buy", irregular: false, aux: "avere", participle: "comprato" },
  { id: "studiare", it: "studiare", en: "to study", irregular: false, aux: "avere", participle: "studiato" },
  { id: "giocare", it: "giocare", en: "to play", irregular: false, aux: "avere", participle: "giocato" },
  { id: "pagare", it: "pagare", en: "to pay", irregular: false, aux: "avere", participle: "pagato" },
  { id: "cominciare", it: "cominciare", en: "to begin", irregular: false, aux: "avere", participle: "cominciato" },
  { id: "finire", it: "finire", en: "to finish", irregular: false, aux: "avere", participle: "finito", isc: true },
  { id: "preferire", it: "preferire", en: "to prefer", irregular: false, aux: "avere", participle: "preferito", isc: true },
  { id: "dormire", it: "dormire", en: "to sleep", irregular: false, aux: "avere", participle: "dormito" },
  { id: "partire", it: "partire", en: "to leave / depart", irregular: false, aux: "essere", participle: "partito" },
  { id: "restare", it: "restare", en: "to remain / stay", irregular: false, aux: "essere", participle: "restato" },
  { id: "abitare", it: "abitare", en: "to live / reside", irregular: false, aux: "avere", participle: "abitato" },
  { id: "ascoltare", it: "ascoltare", en: "to listen to", irregular: false, aux: "avere", participle: "ascoltato" },
  { id: "usare", it: "usare", en: "to use", irregular: false, aux: "avere", participle: "usato" },
  { id: "piacere", it: "piacere", en: "to please / like", irregular: true, aux: "essere", participle: "piaciuto" },
  { id: "sembrare", it: "sembrare", en: "to seem", irregular: false, aux: "essere", participle: "sembrato" },
  { id: "tenere", it: "tenere", en: "to hold / keep", irregular: true, aux: "avere", participle: "tenuto" },
  { id: "riuscire", it: "riuscire", en: "to manage / succeed", irregular: true, aux: "essere", participle: "riuscito" },
  { id: "rimanere", it: "rimanere", en: "to remain", irregular: true, aux: "essere", participle: "rimasto" },
  { id: "cadere", it: "cadere", en: "to fall", irregular: true, aux: "essere", participle: "caduto" },
  { id: "scegliere", it: "scegliere", en: "to choose", irregular: true, aux: "avere", participle: "scelto" },
  { id: "nascere", it: "nascere", en: "to be born", irregular: true, aux: "essere", participle: "nato" },
  { id: "crescere", it: "crescere", en: "to grow", irregular: true, aux: "avere", participle: "cresciuto" },
  { id: "correre", it: "correre", en: "to run", irregular: true, aux: "avere", participle: "corso" },
  { id: "ridere", it: "ridere", en: "to laugh", irregular: true, aux: "avere", participle: "riso" },
  { id: "vincere", it: "vincere", en: "to win", irregular: true, aux: "avere", participle: "vinto" },
  { id: "offrire", it: "offrire", en: "to offer", irregular: true, aux: "avere", participle: "offerto" },
  { id: "produrre", it: "produrre", en: "to produce", irregular: true, aux: "avere", participle: "prodotto" },
  { id: "spiegare", it: "spiegare", en: "to explain", irregular: false, aux: "avere", participle: "spiegato" },
  { id: "seguire", it: "seguire", en: "to follow", irregular: false, aux: "avere", participle: "seguito" },
  { id: "servire", it: "servire", en: "to serve / be useful", irregular: false, aux: "avere", participle: "servito" },
  { id: "ricevere", it: "ricevere", en: "to receive", irregular: false, aux: "avere", participle: "ricevuto" },
  { id: "amare", it: "amare", en: "to love", irregular: false, aux: "avere", participle: "amato" },
  { id: "aiutare", it: "aiutare", en: "to help", irregular: false, aux: "avere", participle: "aiutato" },
  { id: "ricordare", it: "ricordare", en: "to remember", irregular: false, aux: "avere", participle: "ricordato" },
  { id: "dimenticare", it: "dimenticare", en: "to forget", irregular: false, aux: "avere", participle: "dimenticato" },
  { id: "provare", it: "provare", en: "to try", irregular: false, aux: "avere", participle: "provato" },
  { id: "cambiare", it: "cambiare", en: "to change", irregular: false, aux: "avere", participle: "cambiato" },
  { id: "continuare", it: "continuare", en: "to continue", irregular: false, aux: "avere", participle: "continuato" },
  { id: "iniziare", it: "iniziare", en: "to start", irregular: false, aux: "avere", participle: "iniziato" },
  { id: "diventare", it: "diventare", en: "to become", irregular: false, aux: "essere", participle: "diventato" },
  { id: "creare", it: "creare", en: "to create", irregular: false, aux: "avere", participle: "creato" },
  { id: "incontrare", it: "incontrare", en: "to meet", irregular: false, aux: "avere", participle: "incontrato" },
  { id: "mostrare", it: "mostrare", en: "to show", irregular: false, aux: "avere", participle: "mostrato" },
  { id: "succedere", it: "succedere", en: "to happen", irregular: true, aux: "essere", participle: "successo" },
  { id: "esistere", it: "esistere", en: "to exist", irregular: false, aux: "essere", participle: "esistito" },
  { id: "telefonare", it: "telefonare", en: "to phone", irregular: false, aux: "avere", participle: "telefonato" },
  { id: "viaggiare", it: "viaggiare", en: "to travel", irregular: false, aux: "avere", participle: "viaggiato" },
  { id: "camminare", it: "camminare", en: "to walk", irregular: false, aux: "avere", participle: "camminato" },
  { id: "vendere", it: "vendere", en: "to sell", irregular: false, aux: "avere", participle: "venduto" },
  { id: "decidere", it: "decidere", en: "to decide", irregular: true, aux: "avere", participle: "deciso" },
  { id: "permettere", it: "permettere", en: "to allow", irregular: true, aux: "avere", participle: "permesso" },
  { id: "accadere", it: "accadere", en: "to happen / occur", irregular: true, aux: "essere", participle: "accaduto" },
  { id: "ottenere", it: "ottenere", en: "to obtain", irregular: true, aux: "avere", participle: "ottenuto" },
  { id: "riconoscere", it: "riconoscere", en: "to recognize", irregular: false, aux: "avere", participle: "riconosciuto" },
  { id: "costruire", it: "costruire", en: "to build", irregular: false, aux: "avere", participle: "costruito", isc: true },
];

const IRREGULAR_FORMS = {
  essere: {
    presente: ["sono", "sei", "è", "siamo", "siete", "sono"],
    passato_prossimo: ["sono stato/a", "sei stato/a", "è stato/a", "siamo stati/e", "siete stati/e", "sono stati/e"],
    imperfetto: ["ero", "eri", "era", "eravamo", "eravate", "erano"],
    futuro: ["sarò", "sarai", "sarà", "saremo", "sarete", "saranno"],
    condizionale: ["sarei", "saresti", "sarebbe", "saremmo", "sareste", "sarebbero"],
    congiuntivo_presente: ["sia", "sia", "sia", "siamo", "siate", "siano"],
  },
  avere: {
    presente: ["ho", "hai", "ha", "abbiamo", "avete", "hanno"],
    futuro: ["avrò", "avrai", "avrà", "avremo", "avrete", "avranno"],
    condizionale: ["avrei", "avresti", "avrebbe", "avremmo", "avreste", "avrebbero"],
    congiuntivo_presente: ["abbia", "abbia", "abbia", "abbiamo", "abbiate", "abbiano"],
  },
  fare: {
    presente: ["faccio/fo", "fai", "fa", "facciamo", "fate", "fanno"],
    imperfetto: ["facevo", "facevi", "faceva", "facevamo", "facevate", "facevano"],
    futuro: ["farò", "farai", "farà", "faremo", "farete", "faranno"],
    condizionale: ["farei", "faresti", "farebbe", "faremmo", "fareste", "farebbero"],
    congiuntivo_presente: ["faccia", "faccia", "faccia", "facciamo", "facciate", "facciano"],
  },
  dire: {
    presente: ["dico", "dici", "dice", "diciamo", "dite", "dicono"],
    imperfetto: ["dicevo", "dicevi", "diceva", "dicevamo", "dicevate", "dicevano"],
    futuro: ["dirò", "dirai", "dirà", "diremo", "direte", "diranno"],
    condizionale: ["direi", "diresti", "direbbe", "diremmo", "direste", "direbbero"],
    congiuntivo_presente: ["dica", "dica", "dica", "diciamo", "diciate", "dicano"],
  },
  potere: {
    presente: ["posso", "puoi", "può", "possiamo", "potete", "possono"],
    futuro: ["potrò", "potrai", "potrà", "potremo", "potrete", "potranno"],
    condizionale: ["potrei", "potresti", "potrebbe", "potremmo", "potreste", "potrebbero"],
    congiuntivo_presente: ["possa", "possa", "possa", "possiamo", "possiate", "possano"],
  },
  volere: {
    presente: ["voglio/vò", "vuoi", "vuole", "vogliamo", "volete", "vogliono"],
    futuro: ["vorrò", "vorrai", "vorrà", "vorremo", "vorrete", "vorranno"],
    condizionale: ["vorrei", "vorresti", "vorrebbe", "vorremmo", "vorreste", "vorrebbero"],
    congiuntivo_presente: ["voglia", "voglia", "voglia", "vogliamo", "vogliate", "vogliano"],
  },
  dovere: {
    presente: ["devo/debbo", "devi", "deve", "dobbiamo", "dovete", "devono/debbono"],
    futuro: ["dovrò", "dovrai", "dovrà", "dovremo", "dovrete", "dovranno"],
    condizionale: ["dovrei", "dovresti", "dovrebbe", "dovremmo", "dovreste", "dovrebbero"],
    congiuntivo_presente: ["deva/debba", "deva/debba", "deva/debba", "dobbiamo", "dobbiate", "devano/debbano"],
  },
  sapere: {
    presente: ["so", "sai", "sa", "sappiamo", "sapete", "sanno"],
    futuro: ["saprò", "saprai", "saprà", "sapremo", "saprete", "sapranno"],
    condizionale: ["saprei", "sapresti", "saprebbe", "sapremmo", "sapreste", "saprebbero"],
    congiuntivo_presente: ["sappia", "sappia", "sappia", "sappiamo", "sappiate", "sappiano"],
  },
  stare: {
    presente: ["sto", "stai", "sta", "stiamo", "state", "stanno"],
    futuro: ["starò", "starai", "starà", "staremo", "starete", "staranno"],
    condizionale: ["starei", "staresti", "starebbe", "staremmo", "stareste", "starebbero"],
    congiuntivo_presente: ["stia", "stia", "stia", "stiamo", "stiate", "stiano"],
  },
  andare: {
    presente: ["vado", "vai", "va", "andiamo", "andate", "vanno"],
    futuro: ["andrò", "andrai", "andrà", "andremo", "andrete", "andranno"],
    condizionale: ["andrei", "andresti", "andrebbe", "andremmo", "andreste", "andrebbero"],
    congiuntivo_presente: ["vada", "vada", "vada", "andiamo", "andiate", "vadano"],
  },
  venire: {
    presente: ["vengo", "vieni", "viene", "veniamo", "venite", "vengono"],
    futuro: ["verrò", "verrai", "verrà", "verremo", "verrete", "verranno"],
    condizionale: ["verrei", "verresti", "verrebbe", "verremmo", "verreste", "verrebbero"],
    congiuntivo_presente: ["venga", "venga", "venga", "veniamo", "veniate", "vengano"],
  },
  dare: {
    presente: ["do", "dai", "dà", "diamo", "date", "danno"],
    futuro: ["darò", "darai", "darà", "daremo", "darete", "daranno"],
    condizionale: ["darei", "daresti", "darebbe", "daremmo", "dareste", "darebbero"],
    congiuntivo_presente: ["dia", "dia", "dia", "diamo", "diate", "diano"],
  },
  vedere: {
    presente: ["vedo/veggo", "vedi", "vede", "vediamo", "vedete", "vedono/veggono"],
    futuro: ["vedrò/vederò", "vedrai/vederai", "vedrà/vederà", "vedremo/vederemo", "vedrete/vederete", "vedranno/vederanno"],
    condizionale: ["vedrei/vederei", "vedresti/vederesti", "vedrebbe/vederebbe", "vedremmo/vederemmo", "vedreste/vedereste", "vedrebbero/vederebbero"],
    congiuntivo_presente: ["veda/vegga", "veda/vegga", "veda/vegga", "vediamo", "vediate", "vedano/veggano"],
  },
  uscire: {
    presente: ["esco", "esci", "esce", "usciamo", "uscite", "escono"],
    congiuntivo_presente: ["esca", "esca", "esca", "usciamo", "usciate", "escano"],
  },
  vivere: {
    futuro: ["vivrò", "vivrai", "vivrà", "vivremo", "vivrete", "vivranno"],
    condizionale: ["vivrei", "vivresti", "vivrebbe", "vivremmo", "vivreste", "vivrebbero"],
  },
  morire: {
    presente: ["muoio", "muori", "muore", "moriamo", "morite", "muoiono"],
    futuro: ["morirò/morrò", "morirai/morrai", "morirà/morrà", "moriremo/morremo", "morirete/morrete", "moriranno/morranno"],
    condizionale: ["morirei/morrei", "moriresti/morresti", "morirebbe/morrebbe", "moriremmo/morremmo", "morireste/morreste", "morirebbero/morrebbero"],
    congiuntivo_presente: ["muoia", "muoia", "muoia", "moriamo", "moriate", "muoiano"],
  },
  bere: {
    presente: ["bevo", "bevi", "beve", "beviamo", "bevete", "bevono"],
    imperfetto: ["bevevo", "bevevi", "beveva", "bevevamo", "bevevate", "bevevano"],
    futuro: ["berrò", "berrai", "berrà", "berremo", "berrete", "berranno"],
    condizionale: ["berrei", "berresti", "berrebbe", "berremmo", "berreste", "berrebbero"],
    congiuntivo_presente: ["beva", "beva", "beva", "beviamo", "beviate", "bevano"],
  },
  piacere: {
    presente: ["piaccio", "piaci", "piace", "piacciamo/piaciamo", "piacete", "piacciono"],
    congiuntivo_presente: ["piaccia", "piaccia", "piaccia", "piacciamo/piaciamo", "piacciate/piaciate", "piacciano"],
  },
  tenere: {
    presente: ["tengo", "tieni", "tiene", "teniamo", "tenete", "tengono"],
    futuro: ["terrò", "terrai", "terrà", "terremo", "terrete", "terranno"],
    condizionale: ["terrei", "terresti", "terrebbe", "terremmo", "terreste", "terrebbero"],
    congiuntivo_presente: ["tenga", "tenga", "tenga", "teniamo", "teniate", "tengano"],
  },
  riuscire: {
    presente: ["riesco", "riesci", "riesce", "riusciamo", "riuscite", "riescono"],
    congiuntivo_presente: ["riesca", "riesca", "riesca", "riusciamo", "riusciate", "riescano"],
  },
  rimanere: {
    presente: ["rimango", "rimani", "rimane", "rimaniamo", "rimanete", "rimangono"],
    futuro: ["rimarrò", "rimarrai", "rimarrà", "rimarremo", "rimarrete", "rimarranno"],
    condizionale: ["rimarrei", "rimarresti", "rimarrebbe", "rimarremmo", "rimarreste", "rimarrebbero"],
    congiuntivo_presente: ["rimanga", "rimanga", "rimanga", "rimaniamo", "rimaniate", "rimangano"],
  },
  cadere: {
    futuro: ["cadrò", "cadrai", "cadrà", "cadremo", "cadrete", "cadranno"],
    condizionale: ["cadrei", "cadresti", "cadrebbe", "cadremmo", "cadreste", "cadrebbero"],
  },
  scegliere: {
    presente: ["scelgo", "scegli", "sceglie", "scegliamo", "scegliete", "scelgono"],
    futuro: ["sceglierò/scerrò", "sceglierai/scerrai", "sceglierà/scerrà", "sceglieremo/scerremo", "sceglierete/scerrete", "sceglieranno/scerranno"],
    condizionale: ["sceglierei/scerrei", "sceglieresti/scerresti", "sceglierebbe/scerrebbe", "sceglieremmo/scerremmo", "scegliereste/scerreste", "sceglierebbero/scerrebbero"],
    congiuntivo_presente: ["scelga", "scelga", "scelga", "scegliamo", "scegliate", "scelgano"],
  },
  nascere: {
    presente: ["nasco", "nasci", "nasce", "nasciamo", "nascete", "nascono"],
    futuro: ["nascerò", "nascerai", "nascerà", "nasceremo", "nascerete", "nasceranno"],
    congiuntivo_presente: ["nasca", "nasca", "nasca", "nasciamo", "nasciate", "nascano"],
  },
  crescere: {
    presente: ["cresco", "cresci", "cresce", "cresciamo", "crescete", "crescono"],
    congiuntivo_presente: ["cresca", "cresca", "cresca", "cresciamo", "cresciate", "crescano"],
  },
  vincere: {
    presente: ["vinco", "vinci", "vince", "vinciamo", "vincete", "vincono"],
    congiuntivo_presente: ["vinca", "vinca", "vinca", "vinciamo", "vinciate", "vincano"],
  },
  giocare: {
    presente: ["gioco/giuoco", "giochi/giuochi", "gioca/giuoca", "giochiamo", "giocate", "giocano/giuocano"],
    congiuntivo_presente: ["giochi/giuochi", "giochi/giuochi", "giochi/giuochi", "giochiamo", "giochiate", "giochino/giuochino"],
  },
  produrre: {
    presente: ["produco", "produci", "produce", "produciamo", "producete", "producono"],
    imperfetto: ["producevo", "producevi", "produceva", "producevamo", "producevate", "producevano"],
    futuro: ["produrrò", "produrrai", "produrrà", "produrremo", "produrrete", "produrranno"],
    condizionale: ["produrrei", "produrresti", "produrrebbe", "produrremmo", "produrreste", "produrrebbero"],
    congiuntivo_presente: ["produca", "produca", "produca", "produciamo", "produciate", "producano"],
  },
  accadere: {
    futuro: ["accadrò", "accadrai", "accadrà", "accadremo", "accadrete", "accadranno"],
    condizionale: ["accadrei", "accadresti", "accadrebbe", "accadremmo", "accadreste", "accadrebbero"],
  },
  ottenere: {
    presente: ["ottengo", "ottieni", "ottiene", "otteniamo", "ottenete", "ottengono"],
    futuro: ["otterrò", "otterrai", "otterrà", "otterremo", "otterrete", "otterranno"],
    condizionale: ["otterrei", "otterresti", "otterrebbe", "otterremmo", "otterreste", "otterrebbero"],
    congiuntivo_presente: ["ottenga", "ottenga", "ottenga", "otteniamo", "otteniate", "ottengano"],
  },
};
