const PRONOUNS = [
  { it: "io", en: "I" },
  { it: "tu", en: "you" },
  { it: "lui / lei", en: "he / she" },
  { it: "noi", en: "we" },
  { it: "voi", en: "you all" },
  { it: "loro", en: "they" },
];

const FORMS = [
  { id: "presente", it: "presente indicativo", en: "present indicative", hint: "I speak / I am" },
  { id: "passato_prossimo", it: "passato prossimo", en: "present perfect", hint: "I have spoken / I went" },
  { id: "imperfetto", it: "imperfetto", en: "imperfect", hint: "I used to speak" },
  { id: "futuro", it: "futuro semplice", en: "simple future", hint: "I will speak" },
  { id: "condizionale", it: "condizionale presente", en: "present conditional", hint: "I would speak" },
  { id: "congiuntivo_presente", it: "congiuntivo presente", en: "present subjunctive", hint: "that I speak" },
];

const VERB_DATA = [
  { id: "essere", it: "essere", en: "to be", irregular: true, aux: "essere", participle: "stato" },
  { id: "avere", it: "avere", en: "to have", irregular: true, aux: "avere", participle: "avuto" },
  { id: "fare", it: "fare", en: "to do / make", irregular: true, aux: "avere", participle: "fatto" },
  { id: "dire", it: "dire", en: "to say / tell", irregular: true, aux: "avere", participle: "detto" },
  { id: "potere", it: "potere", en: "can / to be able to", irregular: true, aux: "avere", participle: "potuto" },
  { id: "volere", it: "volere", en: "to want", irregular: true, aux: "avere", participle: "voluto" },
  { id: "dovere", it: "dovere", en: "must / to have to", irregular: true, aux: "avere", participle: "dovuto" },
  { id: "sapere", it: "sapere", en: "to know", irregular: true, aux: "avere", participle: "saputo" },
  { id: "stare", it: "stare", en: "to stay / be", irregular: true, aux: "essere", participle: "stato" },
  { id: "andare", it: "andare", en: "to go", irregular: true, aux: "essere", participle: "andato" },
  { id: "venire", it: "venire", en: "to come", irregular: true, aux: "essere", participle: "venuto" },
  { id: "dare", it: "dare", en: "to give", irregular: true, aux: "avere", participle: "dato" },
  { id: "vedere", it: "vedere", en: "to see", irregular: true, aux: "avere", participle: "visto" },
  { id: "parlare", it: "parlare", en: "to speak", irregular: false, aux: "avere", participle: "parlato" },
  { id: "trovare", it: "trovare", en: "to find", irregular: false, aux: "avere", participle: "trovato" },
  { id: "prendere", it: "prendere", en: "to take", irregular: true, aux: "avere", participle: "preso" },
  { id: "mettere", it: "mettere", en: "to put", irregular: true, aux: "avere", participle: "messo" },
  { id: "pensare", it: "pensare", en: "to think", irregular: false, aux: "avere", participle: "pensato" },
  { id: "lasciare", it: "lasciare", en: "to leave / let", irregular: false, aux: "avere", participle: "lasciato" },
  { id: "guardare", it: "guardare", en: "to watch / look at", irregular: false, aux: "avere", participle: "guardato" },
  { id: "chiamare", it: "chiamare", en: "to call", irregular: false, aux: "avere", participle: "chiamato" },
  { id: "arrivare", it: "arrivare", en: "to arrive", irregular: false, aux: "essere", participle: "arrivato" },
  { id: "passare", it: "passare", en: "to pass / spend time", irregular: false, aux: "avere", participle: "passato" },
  { id: "credere", it: "credere", en: "to believe", irregular: false, aux: "avere", participle: "creduto" },
  { id: "portare", it: "portare", en: "to bring / wear", irregular: false, aux: "avere", participle: "portato" },
  { id: "uscire", it: "uscire", en: "to go out", irregular: true, aux: "essere", participle: "uscito" },
  { id: "tornare", it: "tornare", en: "to return", irregular: false, aux: "essere", participle: "tornato" },
  { id: "sentire", it: "sentire", en: "to hear / feel", irregular: false, aux: "avere", participle: "sentito" },
  { id: "vivere", it: "vivere", en: "to live", irregular: true, aux: "avere", participle: "vissuto" },
  { id: "morire", it: "morire", en: "to die", irregular: true, aux: "essere", participle: "morto" },
  { id: "capire", it: "capire", en: "to understand", irregular: false, aux: "avere", participle: "capito", isc: true },
  { id: "mangiare", it: "mangiare", en: "to eat", irregular: false, aux: "avere", participle: "mangiato" },
  { id: "bere", it: "bere", en: "to drink", irregular: true, aux: "avere", participle: "bevuto" },
  { id: "aspettare", it: "aspettare", en: "to wait for", irregular: false, aux: "avere", participle: "aspettato" },
  { id: "cercare", it: "cercare", en: "to look for / search", irregular: false, aux: "avere", participle: "cercato" },
  { id: "entrare", it: "entrare", en: "to enter", irregular: false, aux: "essere", participle: "entrato" },
  { id: "lavorare", it: "lavorare", en: "to work", irregular: false, aux: "avere", participle: "lavorato" },
  { id: "scrivere", it: "scrivere", en: "to write", irregular: true, aux: "avere", participle: "scritto" },
  { id: "leggere", it: "leggere", en: "to read", irregular: true, aux: "avere", participle: "letto" },
  { id: "perdere", it: "perdere", en: "to lose", irregular: true, aux: "avere", participle: "perso" },
  { id: "chiedere", it: "chiedere", en: "to ask", irregular: true, aux: "avere", participle: "chiesto" },
  { id: "rispondere", it: "rispondere", en: "to answer", irregular: true, aux: "avere", participle: "risposto" },
  { id: "chiudere", it: "chiudere", en: "to close", irregular: true, aux: "avere", participle: "chiuso" },
  { id: "aprire", it: "aprire", en: "to open", irregular: true, aux: "avere", participle: "aperto" },
  { id: "conoscere", it: "conoscere", en: "to know / meet", irregular: false, aux: "avere", participle: "conosciuto" },
  { id: "comprare", it: "comprare", en: "to buy", irregular: false, aux: "avere", participle: "comprato" },
  { id: "studiare", it: "studiare", en: "to study", irregular: false, aux: "avere", participle: "studiato" },
  { id: "giocare", it: "giocare", en: "to play", irregular: false, aux: "avere", participle: "giocato" },
  { id: "pagare", it: "pagare", en: "to pay", irregular: false, aux: "avere", participle: "pagato" },
  { id: "cominciare", it: "cominciare", en: "to begin", irregular: false, aux: "avere", participle: "cominciato" },
  { id: "finire", it: "finire", en: "to finish", irregular: false, aux: "avere", participle: "finito", isc: true },
  { id: "preferire", it: "preferire", en: "to prefer", irregular: false, aux: "avere", participle: "preferito", isc: true },
  { id: "dormire", it: "dormire", en: "to sleep", irregular: false, aux: "avere", participle: "dormito" },
  { id: "partire", it: "partire", en: "to leave / depart", irregular: false, aux: "essere", participle: "partito" },
  { id: "restare", it: "restare", en: "to remain / stay", irregular: false, aux: "essere", participle: "restato" },
  { id: "abitare", it: "abitare", en: "to live / reside", irregular: false, aux: "avere", participle: "abitato" },
  { id: "ascoltare", it: "ascoltare", en: "to listen to", irregular: false, aux: "avere", participle: "ascoltato" },
  { id: "usare", it: "usare", en: "to use", irregular: false, aux: "avere", participle: "usato" },
  { id: "piacere", it: "piacere", en: "to please / like", irregular: true, aux: "essere", participle: "piaciuto" },
  { id: "sembrare", it: "sembrare", en: "to seem", irregular: false, aux: "essere", participle: "sembrato" },
  { id: "tenere", it: "tenere", en: "to hold / keep", irregular: true, aux: "avere", participle: "tenuto" },
  { id: "riuscire", it: "riuscire", en: "to manage / succeed", irregular: true, aux: "essere", participle: "riuscito" },
  { id: "rimanere", it: "rimanere", en: "to remain", irregular: true, aux: "essere", participle: "rimasto" },
  { id: "cadere", it: "cadere", en: "to fall", irregular: true, aux: "essere", participle: "caduto" },
  { id: "scegliere", it: "scegliere", en: "to choose", irregular: true, aux: "avere", participle: "scelto" },
  { id: "nascere", it: "nascere", en: "to be born", irregular: true, aux: "essere", participle: "nato" },
  { id: "crescere", it: "crescere", en: "to grow", irregular: true, aux: "avere", participle: "cresciuto" },
  { id: "correre", it: "correre", en: "to run", irregular: true, aux: "avere", participle: "corso" },
  { id: "ridere", it: "ridere", en: "to laugh", irregular: true, aux: "avere", participle: "riso" },
  { id: "vincere", it: "vincere", en: "to win", irregular: true, aux: "avere", participle: "vinto" },
  { id: "offrire", it: "offrire", en: "to offer", irregular: true, aux: "avere", participle: "offerto" },
  { id: "produrre", it: "produrre", en: "to produce", irregular: true, aux: "avere", participle: "prodotto" },
  { id: "spiegare", it: "spiegare", en: "to explain", irregular: false, aux: "avere", participle: "spiegato" },
  { id: "seguire", it: "seguire", en: "to follow", irregular: false, aux: "avere", participle: "seguito" },
  { id: "servire", it: "servire", en: "to serve / be useful", irregular: false, aux: "avere", participle: "servito" },
  { id: "ricevere", it: "ricevere", en: "to receive", irregular: false, aux: "avere", participle: "ricevuto" },
  { id: "amare", it: "amare", en: "to love", irregular: false, aux: "avere", participle: "amato" },
  { id: "aiutare", it: "aiutare", en: "to help", irregular: false, aux: "avere", participle: "aiutato" },
  { id: "ricordare", it: "ricordare", en: "to remember", irregular: false, aux: "avere", participle: "ricordato" },
  { id: "dimenticare", it: "dimenticare", en: "to forget", irregular: false, aux: "avere", participle: "dimenticato" },
  { id: "provare", it: "provare", en: "to try", irregular: false, aux: "avere", participle: "provato" },
  { id: "cambiare", it: "cambiare", en: "to change", irregular: false, aux: "avere", participle: "cambiato" },
  { id: "continuare", it: "continuare", en: "to continue", irregular: false, aux: "avere", participle: "continuato" },
  { id: "iniziare", it: "iniziare", en: "to start", irregular: false, aux: "avere", participle: "iniziato" },
  { id: "diventare", it: "diventare", en: "to become", irregular: false, aux: "essere", participle: "diventato" },
  { id: "creare", it: "creare", en: "to create", irregular: false, aux: "avere", participle: "creato" },
  { id: "incontrare", it: "incontrare", en: "to meet", irregular: false, aux: "avere", participle: "incontrato" },
  { id: "mostrare", it: "mostrare", en: "to show", irregular: false, aux: "avere", participle: "mostrato" },
  { id: "succedere", it: "succedere", en: "to happen", irregular: true, aux: "essere", participle: "successo" },
  { id: "esistere", it: "esistere", en: "to exist", irregular: false, aux: "essere", participle: "esistito" },
  { id: "telefonare", it: "telefonare", en: "to phone", irregular: false, aux: "avere", participle: "telefonato" },
  { id: "viaggiare", it: "viaggiare", en: "to travel", irregular: false, aux: "avere", participle: "viaggiato" },
  { id: "camminare", it: "camminare", en: "to walk", irregular: false, aux: "avere", participle: "camminato" },
  { id: "vendere", it: "vendere", en: "to sell", irregular: false, aux: "avere", participle: "venduto" },
  { id: "decidere", it: "decidere", en: "to decide", irregular: true, aux: "avere", participle: "deciso" },
  { id: "permettere", it: "permettere", en: "to allow", irregular: true, aux: "avere", participle: "permesso" },
  { id: "accadere", it: "accadere", en: "to happen / occur", irregular: true, aux: "essere", participle: "accaduto" },
  { id: "ottenere", it: "ottenere", en: "to obtain", irregular: true, aux: "avere", participle: "ottenuto" },
  { id: "riconoscere", it: "riconoscere", en: "to recognize", irregular: false, aux: "avere", participle: "riconosciuto" },
  { id: "costruire", it: "costruire", en: "to build", irregular: false, aux: "avere", participle: "costruito", isc: true },
  { id: "accendere", it: "accendere", en: "to turn on / light", irregular: true, aux: "avere", participle: "acceso" },
  { id: "accettare", it: "accettare", en: "to accept", irregular: false, aux: "avere", participle: "accettato" },
  { id: "accompagnare", it: "accompagnare", en: "to accompany", irregular: false, aux: "avere", participle: "accompagnato" },
  { id: "aggiungere", it: "aggiungere", en: "to add", irregular: true, aux: "avere", participle: "aggiunto" },
  { id: "alzare", it: "alzare", en: "to raise / lift", irregular: false, aux: "avere", participle: "alzato" },
  { id: "annunciare", it: "annunciare", en: "to announce", irregular: false, aux: "avere", participle: "annunciato" },
  { id: "appartenere", it: "appartenere", en: "to belong", irregular: true, aux: "essere", participle: "appartenuto" },
  { id: "apparire", it: "apparire", en: "to appear", irregular: true, aux: "essere", participle: "apparso" },
  { id: "assistere", it: "assistere", en: "to attend / assist", irregular: false, aux: "avere", participle: "assistito" },
  { id: "assumere", it: "assumere", en: "to hire / assume", irregular: true, aux: "avere", participle: "assunto" },
  { id: "attendere", it: "attendere", en: "to wait for", irregular: true, aux: "avere", participle: "atteso" },
  { id: "attraversare", it: "attraversare", en: "to cross", irregular: false, aux: "avere", participle: "attraversato" },
  { id: "avvicinare", it: "avvicinare", en: "to approach / bring closer", irregular: false, aux: "avere", participle: "avvicinato" },
  { id: "ballare", it: "ballare", en: "to dance", irregular: false, aux: "avere", participle: "ballato" },
  { id: "bastare", it: "bastare", en: "to be enough", irregular: false, aux: "essere", participle: "bastato" },
  { id: "battere", it: "battere", en: "to beat / hit", irregular: false, aux: "avere", participle: "battuto" },
  { id: "buttare", it: "buttare", en: "to throw", irregular: false, aux: "avere", participle: "buttato" },
  { id: "cantare", it: "cantare", en: "to sing", irregular: false, aux: "avere", participle: "cantato" },
  { id: "caricare", it: "caricare", en: "to load / charge", irregular: false, aux: "avere", participle: "caricato" },
  { id: "collaborare", it: "collaborare", en: "to collaborate", irregular: false, aux: "avere", participle: "collaborato" },
  { id: "colpire", it: "colpire", en: "to hit / strike", irregular: false, aux: "avere", participle: "colpito", isc: true },
  { id: "concludere", it: "concludere", en: "to conclude", irregular: true, aux: "avere", participle: "concluso" },
  { id: "condurre", it: "condurre", en: "to lead / conduct", irregular: true, aux: "avere", participle: "condotto" },
  { id: "conservare", it: "conservare", en: "to keep / preserve", irregular: false, aux: "avere", participle: "conservato" },
  { id: "considerare", it: "considerare", en: "to consider", irregular: false, aux: "avere", participle: "considerato" },
  { id: "consigliare", it: "consigliare", en: "to advise", irregular: false, aux: "avere", participle: "consigliato" },
  { id: "contare", it: "contare", en: "to count / matter", irregular: false, aux: "avere", participle: "contato" },
  { id: "contenere", it: "contenere", en: "to contain", irregular: true, aux: "avere", participle: "contenuto" },
  { id: "controllare", it: "controllare", en: "to check / control", irregular: false, aux: "avere", participle: "controllato" },
  { id: "convincere", it: "convincere", en: "to convince", irregular: true, aux: "avere", participle: "convinto" },
  { id: "coprire", it: "coprire", en: "to cover", irregular: true, aux: "avere", participle: "coperto" },
  { id: "costare", it: "costare", en: "to cost", irregular: false, aux: "essere", participle: "costato" },
  { id: "cucinare", it: "cucinare", en: "to cook", irregular: false, aux: "avere", participle: "cucinato" },
  { id: "curare", it: "curare", en: "to care for / treat", irregular: false, aux: "avere", participle: "curato" },
  { id: "descrivere", it: "descrivere", en: "to describe", irregular: true, aux: "avere", participle: "descritto" },
  { id: "difendere", it: "difendere", en: "to defend", irregular: true, aux: "avere", participle: "difeso" },
  { id: "dipingere", it: "dipingere", en: "to paint", irregular: true, aux: "avere", participle: "dipinto" },
  { id: "dirigere", it: "dirigere", en: "to direct / manage", irregular: true, aux: "avere", participle: "diretto" },
  { id: "discutere", it: "discutere", en: "to discuss / argue", irregular: true, aux: "avere", participle: "discusso" },
  { id: "disegnare", it: "disegnare", en: "to draw", irregular: false, aux: "avere", participle: "disegnato" },
  { id: "dividere", it: "dividere", en: "to divide / share", irregular: true, aux: "avere", participle: "diviso" },
  { id: "domandare", it: "domandare", en: "to ask", irregular: false, aux: "avere", participle: "domandato" },
  { id: "educare", it: "educare", en: "to educate", irregular: false, aux: "avere", participle: "educato" },
  { id: "evitare", it: "evitare", en: "to avoid", irregular: false, aux: "avere", participle: "evitato" },
  { id: "firmare", it: "firmare", en: "to sign", irregular: false, aux: "avere", participle: "firmato" },
  { id: "funzionare", it: "funzionare", en: "to work / function", irregular: false, aux: "avere", participle: "funzionato" },
  { id: "gettare", it: "gettare", en: "to throw", irregular: false, aux: "avere", participle: "gettato" },
  { id: "guidare", it: "guidare", en: "to drive / guide", irregular: false, aux: "avere", participle: "guidato" },
  { id: "indicare", it: "indicare", en: "to indicate / point out", irregular: false, aux: "avere", participle: "indicato" },
  { id: "influenzare", it: "influenzare", en: "to influence", irregular: false, aux: "avere", participle: "influenzato" },
  { id: "insegnare", it: "insegnare", en: "to teach", irregular: false, aux: "avere", participle: "insegnato" },
  { id: "intendere", it: "intendere", en: "to intend / mean", irregular: true, aux: "avere", participle: "inteso" },
  { id: "interessare", it: "interessare", en: "to interest", irregular: false, aux: "avere", participle: "interessato" },
  { id: "invitare", it: "invitare", en: "to invite", irregular: false, aux: "avere", participle: "invitato" },
  { id: "lavare", it: "lavare", en: "to wash", irregular: false, aux: "avere", participle: "lavato" },
  { id: "mandare", it: "mandare", en: "to send", irregular: false, aux: "avere", participle: "mandato" },
  { id: "mancare", it: "mancare", en: "to be missing / miss", irregular: false, aux: "essere", participle: "mancato" },
  { id: "mantenere", it: "mantenere", en: "to maintain / keep", irregular: true, aux: "avere", participle: "mantenuto" },
  { id: "migliorare", it: "migliorare", en: "to improve", irregular: false, aux: "avere", participle: "migliorato" },
  { id: "nominare", it: "nominare", en: "to name / appoint", irregular: false, aux: "avere", participle: "nominato" },
  { id: "nuotare", it: "nuotare", en: "to swim", irregular: false, aux: "avere", participle: "nuotato" },
  { id: "occupare", it: "occupare", en: "to occupy / take up", irregular: false, aux: "avere", participle: "occupato" },
  { id: "ordinare", it: "ordinare", en: "to order / arrange", irregular: false, aux: "avere", participle: "ordinato" },
  { id: "organizzare", it: "organizzare", en: "to organize", irregular: false, aux: "avere", participle: "organizzato" },
  { id: "parcheggiare", it: "parcheggiare", en: "to park", irregular: false, aux: "avere", participle: "parcheggiato" },
  { id: "partecipare", it: "partecipare", en: "to participate", irregular: false, aux: "avere", participle: "partecipato" },
  { id: "pesare", it: "pesare", en: "to weigh", irregular: false, aux: "avere", participle: "pesato" },
  { id: "porre", it: "porre", en: "to place / put", irregular: true, aux: "avere", participle: "posto" },
  { id: "praticare", it: "praticare", en: "to practice", irregular: false, aux: "avere", participle: "praticato" },
  { id: "preparare", it: "preparare", en: "to prepare", irregular: false, aux: "avere", participle: "preparato" },
  { id: "presentare", it: "presentare", en: "to present / introduce", irregular: false, aux: "avere", participle: "presentato" },
  { id: "prestare", it: "prestare", en: "to lend", irregular: false, aux: "avere", participle: "prestato" },
  { id: "promettere", it: "promettere", en: "to promise", irregular: true, aux: "avere", participle: "promesso" },
  { id: "proporre", it: "proporre", en: "to propose / suggest", irregular: true, aux: "avere", participle: "proposto" },
  { id: "proteggere", it: "proteggere", en: "to protect", irregular: true, aux: "avere", participle: "protetto" },
  { id: "pubblicare", it: "pubblicare", en: "to publish", irregular: false, aux: "avere", participle: "pubblicato" },
  { id: "pulire", it: "pulire", en: "to clean", irregular: false, aux: "avere", participle: "pulito", isc: true },
  { id: "raccogliere", it: "raccogliere", en: "to collect / pick up", irregular: true, aux: "avere", participle: "raccolto" },
  { id: "raccontare", it: "raccontare", en: "to tell / narrate", irregular: false, aux: "avere", participle: "raccontato" },
  { id: "raggiungere", it: "raggiungere", en: "to reach", irregular: true, aux: "avere", participle: "raggiunto" },
  { id: "realizzare", it: "realizzare", en: "to realize / make", irregular: false, aux: "avere", participle: "realizzato" },
  { id: "recitare", it: "recitare", en: "to act / recite", irregular: false, aux: "avere", participle: "recitato" },
  { id: "rendere", it: "rendere", en: "to make / render", irregular: true, aux: "avere", participle: "reso" },
  { id: "ringraziare", it: "ringraziare", en: "to thank", irregular: false, aux: "avere", participle: "ringraziato" },
  { id: "ripetere", it: "ripetere", en: "to repeat", irregular: false, aux: "avere", participle: "ripetuto" },
  { id: "risolvere", it: "risolvere", en: "to solve", irregular: true, aux: "avere", participle: "risolto" },
  { id: "rompere", it: "rompere", en: "to break", irregular: true, aux: "avere", participle: "rotto" },
  { id: "salire", it: "salire", en: "to go up / climb", irregular: true, aux: "essere", participle: "salito" },
  { id: "saltare", it: "saltare", en: "to jump / skip", irregular: false, aux: "avere", participle: "saltato" },
  { id: "salutare", it: "salutare", en: "to greet", irregular: false, aux: "avere", participle: "salutato" },
  { id: "salvare", it: "salvare", en: "to save", irregular: false, aux: "avere", participle: "salvato" },
  { id: "scendere", it: "scendere", en: "to go down / descend", irregular: true, aux: "essere", participle: "sceso" },
  { id: "scherzare", it: "scherzare", en: "to joke", irregular: false, aux: "avere", participle: "scherzato" },
  { id: "scoprire", it: "scoprire", en: "to discover", irregular: true, aux: "avere", participle: "scoperto" },
  { id: "smettere", it: "smettere", en: "to stop / quit", irregular: true, aux: "avere", participle: "smesso" },
  { id: "sognare", it: "sognare", en: "to dream", irregular: false, aux: "avere", participle: "sognato" },
  { id: "sostenere", it: "sostenere", en: "to support / sustain", irregular: true, aux: "avere", participle: "sostenuto" },
  { id: "sostituire", it: "sostituire", en: "to replace", irregular: false, aux: "avere", participle: "sostituito", isc: true },
  { id: "spedire", it: "spedire", en: "to send / ship", irregular: false, aux: "avere", participle: "spedito", isc: true },
  { id: "spegnere", it: "spegnere", en: "to turn off", irregular: true, aux: "avere", participle: "spento" },
  { id: "spendere", it: "spendere", en: "to spend", irregular: true, aux: "avere", participle: "speso" },
  { id: "sperare", it: "sperare", en: "to hope", irregular: false, aux: "avere", participle: "sperato" },
  { id: "spingere", it: "spingere", en: "to push", irregular: true, aux: "avere", participle: "spinto" },
  { id: "sposare", it: "sposare", en: "to marry", irregular: false, aux: "avere", participle: "sposato" },
  { id: "stampare", it: "stampare", en: "to print", irregular: false, aux: "avere", participle: "stampato" },
  { id: "suggerire", it: "suggerire", en: "to suggest", irregular: false, aux: "avere", participle: "suggerito", isc: true },
  { id: "suonare", it: "suonare", en: "to play / sound", irregular: false, aux: "avere", participle: "suonato" },
  { id: "tirare", it: "tirare", en: "to pull / throw", irregular: false, aux: "avere", participle: "tirato" },
  { id: "tradurre", it: "tradurre", en: "to translate", irregular: true, aux: "avere", participle: "tradotto" },
  { id: "uccidere", it: "uccidere", en: "to kill", irregular: true, aux: "avere", participle: "ucciso" },
  { id: "unire", it: "unire", en: "to unite / join", irregular: false, aux: "avere", participle: "unito", isc: true },
  { id: "urlare", it: "urlare", en: "to shout", irregular: false, aux: "avere", participle: "urlato" },
  { id: "valere", it: "valere", en: "to be worth", irregular: true, aux: "avere", participle: "valso" },
  { id: "vestire", it: "vestire", en: "to dress / wear", irregular: false, aux: "avere", participle: "vestito" },
  { id: "visitare", it: "visitare", en: "to visit", irregular: false, aux: "avere", participle: "visitato" },
  { id: "votare", it: "votare", en: "to vote", irregular: false, aux: "avere", participle: "votato" },
  { id: "coniugare", it: "coniugare", en: "to conjugate", irregular: false, aux: "avere", participle: "coniugato" },
];

const IRREGULAR_FORMS = {
  essere: {
    presente: ["sono", "sei", "è", "siamo", "siete", "sono"],
    passato_prossimo: ["sono stato/a", "sei stato/a", "è stato/a", "siamo stati/e", "siete stati/e", "sono stati/e"],
    imperfetto: ["ero", "eri", "era", "eravamo", "eravate", "erano"],
    futuro: ["sarò", "sarai", "sarà", "saremo", "sarete", "saranno"],
    condizionale: ["sarei", "saresti", "sarebbe", "saremmo", "sareste", "sarebbero"],
    congiuntivo_presente: ["sia", "sia", "sia", "siamo", "siate", "siano"],
  },
  avere: {
    presente: ["ho", "hai", "ha", "abbiamo", "avete", "hanno"],
    futuro: ["avrò", "avrai", "avrà", "avremo", "avrete", "avranno"],
    condizionale: ["avrei", "avresti", "avrebbe", "avremmo", "avreste", "avrebbero"],
    congiuntivo_presente: ["abbia", "abbia", "abbia", "abbiamo", "abbiate", "abbiano"],
  },
  fare: {
    presente: ["faccio/fo", "fai", "fa", "facciamo", "fate", "fanno"],
    imperfetto: ["facevo", "facevi", "faceva", "facevamo", "facevate", "facevano"],
    futuro: ["farò", "farai", "farà", "faremo", "farete", "faranno"],
    condizionale: ["farei", "faresti", "farebbe", "faremmo", "fareste", "farebbero"],
    congiuntivo_presente: ["faccia", "faccia", "faccia", "facciamo", "facciate", "facciano"],
  },
  dire: {
    presente: ["dico", "dici", "dice", "diciamo", "dite", "dicono"],
    imperfetto: ["dicevo", "dicevi", "diceva", "dicevamo", "dicevate", "dicevano"],
    futuro: ["dirò", "dirai", "dirà", "diremo", "direte", "diranno"],
    condizionale: ["direi", "diresti", "direbbe", "diremmo", "direste", "direbbero"],
    congiuntivo_presente: ["dica", "dica", "dica", "diciamo", "diciate", "dicano"],
  },
  potere: {
    presente: ["posso", "puoi", "può", "possiamo", "potete", "possono"],
    futuro: ["potrò", "potrai", "potrà", "potremo", "potrete", "potranno"],
    condizionale: ["potrei", "potresti", "potrebbe", "potremmo", "potreste", "potrebbero"],
    congiuntivo_presente: ["possa", "possa", "possa", "possiamo", "possiate", "possano"],
  },
  volere: {
    presente: ["voglio/vò", "vuoi", "vuole", "vogliamo", "volete", "vogliono"],
    futuro: ["vorrò", "vorrai", "vorrà", "vorremo", "vorrete", "vorranno"],
    condizionale: ["vorrei", "vorresti", "vorrebbe", "vorremmo", "vorreste", "vorrebbero"],
    congiuntivo_presente: ["voglia", "voglia", "voglia", "vogliamo", "vogliate", "vogliano"],
  },
  dovere: {
    presente: ["devo/debbo", "devi", "deve", "dobbiamo", "dovete", "devono/debbono"],
    futuro: ["dovrò", "dovrai", "dovrà", "dovremo", "dovrete", "dovranno"],
    condizionale: ["dovrei", "dovresti", "dovrebbe", "dovremmo", "dovreste", "dovrebbero"],
    congiuntivo_presente: ["deva/debba", "deva/debba", "deva/debba", "dobbiamo", "dobbiate", "devano/debbano"],
  },
  sapere: {
    presente: ["so", "sai", "sa", "sappiamo", "sapete", "sanno"],
    futuro: ["saprò", "saprai", "saprà", "sapremo", "saprete", "sapranno"],
    condizionale: ["saprei", "sapresti", "saprebbe", "sapremmo", "sapreste", "saprebbero"],
    congiuntivo_presente: ["sappia", "sappia", "sappia", "sappiamo", "sappiate", "sappiano"],
  },
  stare: {
    presente: ["sto", "stai", "sta", "stiamo", "state", "stanno"],
    futuro: ["starò", "starai", "starà", "staremo", "starete", "staranno"],
    condizionale: ["starei", "staresti", "starebbe", "staremmo", "stareste", "starebbero"],
    congiuntivo_presente: ["stia", "stia", "stia", "stiamo", "stiate", "stiano"],
  },
  andare: {
    presente: ["vado", "vai", "va", "andiamo", "andate", "vanno"],
    futuro: ["andrò", "andrai", "andrà", "andremo", "andrete", "andranno"],
    condizionale: ["andrei", "andresti", "andrebbe", "andremmo", "andreste", "andrebbero"],
    congiuntivo_presente: ["vada", "vada", "vada", "andiamo", "andiate", "vadano"],
  },
  venire: {
    presente: ["vengo", "vieni", "viene", "veniamo", "venite", "vengono"],
    futuro: ["verrò", "verrai", "verrà", "verremo", "verrete", "verranno"],
    condizionale: ["verrei", "verresti", "verrebbe", "verremmo", "verreste", "verrebbero"],
    congiuntivo_presente: ["venga", "venga", "venga", "veniamo", "veniate", "vengano"],
  },
  dare: {
    presente: ["do", "dai", "dà", "diamo", "date", "danno"],
    futuro: ["darò", "darai", "darà", "daremo", "darete", "daranno"],
    condizionale: ["darei", "daresti", "darebbe", "daremmo", "dareste", "darebbero"],
    congiuntivo_presente: ["dia", "dia", "dia", "diamo", "diate", "diano"],
  },
  vedere: {
    presente: ["vedo/veggo", "vedi", "vede", "vediamo", "vedete", "vedono/veggono"],
    futuro: ["vedrò/vederò", "vedrai/vederai", "vedrà/vederà", "vedremo/vederemo", "vedrete/vederete", "vedranno/vederanno"],
    condizionale: ["vedrei/vederei", "vedresti/vederesti", "vedrebbe/vederebbe", "vedremmo/vederemmo", "vedreste/vedereste", "vedrebbero/vederebbero"],
    congiuntivo_presente: ["veda/vegga", "veda/vegga", "veda/vegga", "vediamo", "vediate", "vedano/veggano"],
  },
  uscire: {
    presente: ["esco", "esci", "esce", "usciamo", "uscite", "escono"],
    congiuntivo_presente: ["esca", "esca", "esca", "usciamo", "usciate", "escano"],
  },
  vivere: {
    futuro: ["vivrò", "vivrai", "vivrà", "vivremo", "vivrete", "vivranno"],
    condizionale: ["vivrei", "vivresti", "vivrebbe", "vivremmo", "vivreste", "vivrebbero"],
  },
  morire: {
    presente: ["muoio", "muori", "muore", "moriamo", "morite", "muoiono"],
    futuro: ["morirò/morrò", "morirai/morrai", "morirà/morrà", "moriremo/morremo", "morirete/morrete", "moriranno/morranno"],
    condizionale: ["morirei/morrei", "moriresti/morresti", "morirebbe/morrebbe", "moriremmo/morremmo", "morireste/morreste", "morirebbero/morrebbero"],
    congiuntivo_presente: ["muoia", "muoia", "muoia", "moriamo", "moriate", "muoiano"],
  },
  bere: {
    presente: ["bevo", "bevi", "beve", "beviamo", "bevete", "bevono"],
    imperfetto: ["bevevo", "bevevi", "beveva", "bevevamo", "bevevate", "bevevano"],
    futuro: ["berrò", "berrai", "berrà", "berremo", "berrete", "berranno"],
    condizionale: ["berrei", "berresti", "berrebbe", "berremmo", "berreste", "berrebbero"],
    congiuntivo_presente: ["beva", "beva", "beva", "beviamo", "beviate", "bevano"],
  },
  piacere: {
    presente: ["piaccio", "piaci", "piace", "piacciamo/piaciamo", "piacete", "piacciono"],
    congiuntivo_presente: ["piaccia", "piaccia", "piaccia", "piacciamo/piaciamo", "piacciate/piaciate", "piacciano"],
  },
  tenere: {
    presente: ["tengo", "tieni", "tiene", "teniamo", "tenete", "tengono"],
    futuro: ["terrò", "terrai", "terrà", "terremo", "terrete", "terranno"],
    condizionale: ["terrei", "terresti", "terrebbe", "terremmo", "terreste", "terrebbero"],
    congiuntivo_presente: ["tenga", "tenga", "tenga", "teniamo", "teniate", "tengano"],
  },
  riuscire: {
    presente: ["riesco", "riesci", "riesce", "riusciamo", "riuscite", "riescono"],
    congiuntivo_presente: ["riesca", "riesca", "riesca", "riusciamo", "riusciate", "riescano"],
  },
  rimanere: {
    presente: ["rimango", "rimani", "rimane", "rimaniamo", "rimanete", "rimangono"],
    futuro: ["rimarrò", "rimarrai", "rimarrà", "rimarremo", "rimarrete", "rimarranno"],
    condizionale: ["rimarrei", "rimarresti", "rimarrebbe", "rimarremmo", "rimarreste", "rimarrebbero"],
    congiuntivo_presente: ["rimanga", "rimanga", "rimanga", "rimaniamo", "rimaniate", "rimangano"],
  },
  cadere: {
    futuro: ["cadrò", "cadrai", "cadrà", "cadremo", "cadrete", "cadranno"],
    condizionale: ["cadrei", "cadresti", "cadrebbe", "cadremmo", "cadreste", "cadrebbero"],
  },
  scegliere: {
    presente: ["scelgo", "scegli", "sceglie", "scegliamo", "scegliete", "scelgono"],
    futuro: ["sceglierò/scerrò", "sceglierai/scerrai", "sceglierà/scerrà", "sceglieremo/scerremo", "sceglierete/scerrete", "sceglieranno/scerranno"],
    condizionale: ["sceglierei/scerrei", "sceglieresti/scerresti", "sceglierebbe/scerrebbe", "sceglieremmo/scerremmo", "scegliereste/scerreste", "sceglierebbero/scerrebbero"],
    congiuntivo_presente: ["scelga", "scelga", "scelga", "scegliamo", "scegliate", "scelgano"],
  },
  nascere: {
    presente: ["nasco", "nasci", "nasce", "nasciamo", "nascete", "nascono"],
    futuro: ["nascerò", "nascerai", "nascerà", "nasceremo", "nascerete", "nasceranno"],
    congiuntivo_presente: ["nasca", "nasca", "nasca", "nasciamo", "nasciate", "nascano"],
  },
  crescere: {
    presente: ["cresco", "cresci", "cresce", "cresciamo", "crescete", "crescono"],
    congiuntivo_presente: ["cresca", "cresca", "cresca", "cresciamo", "cresciate", "crescano"],
  },
  vincere: {
    presente: ["vinco", "vinci", "vince", "vinciamo", "vincete", "vincono"],
    congiuntivo_presente: ["vinca", "vinca", "vinca", "vinciamo", "vinciate", "vincano"],
  },
  giocare: {
    presente: ["gioco/giuoco", "giochi/giuochi", "gioca/giuoca", "giochiamo", "giocate", "giocano/giuocano"],
    congiuntivo_presente: ["giochi/giuochi", "giochi/giuochi", "giochi/giuochi", "giochiamo", "giochiate", "giochino/giuochino"],
  },
  produrre: {
    presente: ["produco", "produci", "produce", "produciamo", "producete", "producono"],
    imperfetto: ["producevo", "producevi", "produceva", "producevamo", "producevate", "producevano"],
    futuro: ["produrrò", "produrrai", "produrrà", "produrremo", "produrrete", "produrranno"],
    condizionale: ["produrrei", "produrresti", "produrrebbe", "produrremmo", "produrreste", "produrrebbero"],
    congiuntivo_presente: ["produca", "produca", "produca", "produciamo", "produciate", "producano"],
  },
  accadere: {
    futuro: ["accadrò", "accadrai", "accadrà", "accadremo", "accadrete", "accadranno"],
    condizionale: ["accadrei", "accadresti", "accadrebbe", "accadremmo", "accadreste", "accadrebbero"],
  },
  ottenere: {
    presente: ["ottengo", "ottieni", "ottiene", "otteniamo", "ottenete", "ottengono"],
    futuro: ["otterrò", "otterrai", "otterrà", "otterremo", "otterrete", "otterranno"],
    condizionale: ["otterrei", "otterresti", "otterrebbe", "otterremmo", "otterreste", "otterrebbero"],
    congiuntivo_presente: ["ottenga", "ottenga", "ottenga", "otteniamo", "otteniate", "ottengano"],
  },
  appartenere: {
    presente: ["appartengo", "appartieni", "appartiene", "apparteniamo", "appartenete", "appartengono"],
    futuro: ["apparterrò", "apparterrai", "apparterrà", "apparterremo", "apparterrete", "apparterranno"],
    condizionale: ["apparterrei", "apparterresti", "apparterrebbe", "apparterremmo", "apparterreste", "apparterrebbero"],
    congiuntivo_presente: ["appartenga", "appartenga", "appartenga", "apparteniamo", "apparteniate", "appartengano"],
  },
  apparire: {
    presente: ["appaio", "appari", "appare", "appariamo", "apparite", "appaiono"],
    congiuntivo_presente: ["appaia", "appaia", "appaia", "appariamo", "appariate", "appaiano"],
  },
  condurre: {
    presente: ["conduco", "conduci", "conduce", "conduciamo", "conducete", "conducono"],
    imperfetto: ["conducevo", "conducevi", "conduceva", "conducevamo", "conducevate", "conducevano"],
    futuro: ["condurrò", "condurrai", "condurrà", "condurremo", "condurrete", "condurranno"],
    condizionale: ["condurrei", "condurresti", "condurrebbe", "condurremmo", "condurreste", "condurrebbero"],
    congiuntivo_presente: ["conduca", "conduca", "conduca", "conduciamo", "conduciate", "conducano"],
  },
  contenere: {
    presente: ["contengo", "contieni", "contiene", "conteniamo", "contenete", "contengono"],
    futuro: ["conterrò", "conterrai", "conterrà", "conterremo", "conterrete", "conterranno"],
    condizionale: ["conterrei", "conterresti", "conterrebbe", "conterremmo", "conterreste", "conterrebbero"],
    congiuntivo_presente: ["contenga", "contenga", "contenga", "conteniamo", "conteniate", "contengano"],
  },
  mantenere: {
    presente: ["mantengo", "mantieni", "mantiene", "manteniamo", "mantenete", "mantengono"],
    futuro: ["manterrò", "manterrai", "manterrà", "manterremo", "manterrete", "manterranno"],
    condizionale: ["manterrei", "manterresti", "manterrebbe", "manterremmo", "manterreste", "manterrebbero"],
    congiuntivo_presente: ["mantenga", "mantenga", "mantenga", "manteniamo", "manteniate", "mantengano"],
  },
  porre: {
    presente: ["pongo", "poni", "pone", "poniamo", "ponete", "pongono"],
    imperfetto: ["ponevo", "ponevi", "poneva", "ponevamo", "ponevate", "ponevano"],
    futuro: ["porrò", "porrai", "porrà", "porremo", "porrete", "porranno"],
    condizionale: ["porrei", "porresti", "porrebbe", "porremmo", "porreste", "porrebbero"],
    congiuntivo_presente: ["ponga", "ponga", "ponga", "poniamo", "poniate", "pongano"],
  },
  proporre: {
    presente: ["propongo", "proponi", "propone", "proponiamo", "proponete", "propongono"],
    imperfetto: ["proponevo", "proponevi", "proponeva", "proponevamo", "proponevate", "proponevano"],
    futuro: ["proporrò", "proporrai", "proporrà", "proporremo", "proporrete", "proporranno"],
    condizionale: ["proporrei", "proporresti", "proporrebbe", "proporremmo", "proporreste", "proporrebbero"],
    congiuntivo_presente: ["proponga", "proponga", "proponga", "proponiamo", "proponiate", "propongano"],
  },
  raccogliere: {
    presente: ["raccolgo", "raccogli", "raccoglie", "raccogliamo", "raccogliete", "raccolgono"],
    congiuntivo_presente: ["raccolga", "raccolga", "raccolga", "raccogliamo", "raccogliate", "raccolgano"],
  },
  salire: {
    presente: ["salgo", "sali", "sale", "saliamo", "salite", "salgono"],
    congiuntivo_presente: ["salga", "salga", "salga", "saliamo", "saliate", "salgano"],
  },
  sostenere: {
    presente: ["sostengo", "sostieni", "sostiene", "sosteniamo", "sostenete", "sostengono"],
    futuro: ["sosterrò", "sosterrai", "sosterrà", "sosterremo", "sosterrete", "sosterranno"],
    condizionale: ["sosterrei", "sosterresti", "sosterrebbe", "sosterremmo", "sosterreste", "sosterrebbero"],
    congiuntivo_presente: ["sostenga", "sostenga", "sostenga", "sosteniamo", "sosteniate", "sostengano"],
  },
  tradurre: {
    presente: ["traduco", "traduci", "traduce", "traduciamo", "traducete", "traducono"],
    imperfetto: ["traducevo", "traducevi", "traduceva", "traducevamo", "traducevate", "traducevano"],
    futuro: ["tradurrò", "tradurrai", "tradurrà", "tradurremo", "tradurrete", "tradurranno"],
    condizionale: ["tradurrei", "tradurresti", "tradurrebbe", "tradurremmo", "tradurreste", "tradurrebbero"],
    congiuntivo_presente: ["traduca", "traduca", "traduca", "traduciamo", "traduciate", "traducano"],
  },
  valere: {
    presente: ["valgo", "vali", "vale", "valiamo", "valete", "valgono"],
    futuro: ["varrò", "varrai", "varrà", "varremo", "varrete", "varranno"],
    condizionale: ["varrei", "varresti", "varrebbe", "varremmo", "varreste", "varrebbero"],
    congiuntivo_presente: ["valga", "valga", "valga", "valiamo", "valiate", "valgano"],
  },
};
